<a href="https://colab.research.google.com/github/LeQuXi/numerical-methods-secant-chord-false-position-/blob/main/Gaussian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def partial_pivoting(A,b):
    copy_A = np.copy(A)
    copy_b = np.copy(b)
    print(copy_A,copy_b)
    
    for j in range(0,len(A[:]-1)):

        row_max = np.argmax(copy_A[j:,j])
        copy2_A = np.copy(copy_A)
        copy2_b = np.copy(copy_b)
        copy_A[row_max + j,:] = copy2_A[j,:]
        copy_A[j,:] = copy2_A[row_max +j,:]
        copy_b[row_max+j] = copy2_b[j]
        copy_b[j] = copy2_b[row_max + j]
        
        if row_max + j != j:
            print(copy_A,copy_b)
    return copy_A,copy_b
def elimination(A,b):
    print('--------------------')
    copy_A = np.copy(A)
    copy_b = np.copy(b)
    print(copy_A,copy_b)

    for i in range(1,len(A)):
        for j in range(0,i):
            if copy_A[i,j] != 0:
                copy2_A = np.copy(copy_A)
                copy2_b = np.copy(copy_b)
                
                copy_A[i,:] = (copy2_A[i,:]/copy2_A[i,j])*copy2_A[j,j] - copy2_A[j,:]
                copy_b[i] = (copy2_b[i]/copy2_A[i,j])*copy2_A[j,j] - copy2_b[j]
                print(copy_A,copy_b)
           
    return copy_A, copy_b


def back_substitution(A,b):
    solution = np.zeros(len(b))
    for i in range(len(A) -1,-1,-1):
        term = b[i]
        for j in range(len(A[:]) -1 ,i,-1):
          # if(A[i,i]==0):
          #   print("Error")
            term -= A[i,j]*solution[j]
            # if(A[i,i]==0):
            #   print("Error"
        solution[i] = term/A[i,i]
    return solution


def Gauss(A,b):
    pivot = partial_pivoting(a,b)
    elimi = elimination(pivot[0],pivot[1])
    return back_substitution(elimi[0],elimi[1])
    
#a = np.float64([[0, 5, -1],[13,0,1],[1,-1,-1]])
#b = np.float64([4,15,0])
# 7 
# a = np.float64([[2,5,1,2],
#               [-2,3,0,5],
#               [1,0,-1,1],
#               [-3,-4,1,1]])
# b=np.float64([14,10,4,-6])
# 3 
# a = np.float64([[0,1,2,1],
#               [6,-2,3,4],
#               [0,3,4,-3],
#               [0,-4,3,1]])
# b=np.float64([2,-15,10,-2])
#4 
a = np.float64([[3,7,1,3],
              [1,-6,6,8],
              [4,4,-7,1],
              [4,16,2,0]])
b=np.float64([40,19,36,48])


#n =len(b)
t1 = Gauss(a,b)
print(t1)

[[ 3.  7.  1.  3.]
 [ 1. -6.  6.  8.]
 [ 4.  4. -7.  1.]
 [ 4. 16.  2.  0.]] [40. 19. 36. 48.]
[[ 4.  4. -7.  1.]
 [ 1. -6.  6.  8.]
 [ 3.  7.  1.  3.]
 [ 4. 16.  2.  0.]] [36. 19. 40. 48.]
[[ 4.  4. -7.  1.]
 [ 4. 16.  2.  0.]
 [ 3.  7.  1.  3.]
 [ 1. -6.  6.  8.]] [36. 48. 40. 19.]
[[ 4.  4. -7.  1.]
 [ 4. 16.  2.  0.]
 [ 1. -6.  6.  8.]
 [ 3.  7.  1.  3.]] [36. 48. 19. 40.]
--------------------
[[ 4.  4. -7.  1.]
 [ 4. 16.  2.  0.]
 [ 1. -6.  6.  8.]
 [ 3.  7.  1.  3.]] [36. 48. 19. 40.]
[[ 4.  4. -7.  1.]
 [ 0. 12.  9. -1.]
 [ 1. -6.  6.  8.]
 [ 3.  7.  1.  3.]] [36. 12. 19. 40.]
[[  4.   4.  -7.   1.]
 [  0.  12.   9.  -1.]
 [  0. -28.  31.  31.]
 [  3.   7.   1.   3.]] [36. 12. 40. 40.]
[[  4.           4.          -7.           1.        ]
 [  0.          12.           9.          -1.        ]
 [ -0.           0.         -22.28571429 -12.28571429]
 [  3.           7.           1.           3.        ]] [ 36.          12.         -29.14285714  40.        ]
[[  4.           4.    

# 5 no solition
# a = np.float64([[1,2,1,0], 
#               [2,5,0,4],
#               [14,-8,4,1],
#               [4,10,0,8]])
# b=np.float64([-4,3,7,2])
# 2 crashes
# a = np.float64([[3,7,1,3],
#               [1,-6,6,9],
#               [4,4,-7,1],
#               [-1,3,8,2]])
# b=np.float64([37,11,38,-1])